HW09 is completed
yakuninmax/otus_go pull request #13
Opened 2024-07-19 20:43 UTC by yakuninmax

## Домашнее задание №9 «Валидатор структур»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2024-07-20 10:10 UTC, dshemin requested changes

2024-07-20 10:10 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	for i := 0; i < inputStructType.NumField(); i++ {
Критично:

Обратите внимание на задание:
```
Она должна валидировать публичные поля входной структуры
```

Надо валидировать только публичные поля.

2024-07-20 10:10 UTC, dshemin commented on hw09_struct_validator/int_validator.go
> +			log.Println("reference value is not int")
Критично:

Обратите внимание на текст задания:
```
Функция может возвращать

или программную ошибку, произошедшую во время валидации;
или ValidationErrors - ошибку, являющуюся слайсом структур, содержащих имя поля и ошибку его валидации.
```

А  также ниже:
```
Частые ошибки

...
Нет разделения на программные ошибки (неверный тэг, регулярка и пр.) и ошибки валидации.
...
```

2024-07-22 21:08 UTC, yakuninmax commented on hw09_struct_validator/validator.go
> +	for i := 0; i < inputStructType.NumField(); i++ {
Исправил

2024-07-22 21:08 UTC, yakuninmax commented on hw09_struct_validator/int_validator.go
> +			log.Println("reference value is not int")
Исправил.

2024-07-23 02:30 UTC, dshemin approved these changes

2024-07-23 02:30 UTC, dshemin commented on hw09_struct_validator/int_validator.go
> +			return ErrInvalidRule
Важно:

Тут лучше обернуть исходную ошибку, иначе будет сложно отлаживать так, как разработчику будет непонятно что именно он не так сделал.

2024-07-23 08:47 UTC, yakuninmax commented on hw09_struct_validator/int_validator.go
> +			return ErrInvalidRule
Исправлено.

2024-07-25 18:14 UTC, dshemin approved these changes

2024-07-25 18:14 UTC, dshemin commented on hw09_struct_validator/int_validator.go
> +			return CommonError{CommonErr: ErrInvalidRef}
Важно:

Про обораивание, я имел ввиду что надо вернуть исходную ошибку, которую нам вернул atoi. Иначе как разработчик поймёт что именно он не так сделал. Если пишите библиотеку, то вашим пользователем является другой программист. Подумайте, было бы вам удобно пользоваться вашим решением.

2024-07-25 22:15 UTC, yakuninmax commented on hw09_struct_validator/int_validator.go
> +			return CommonError{CommonErr: ErrInvalidRef}
Понял. Исправил.

2024-08-01 20:19 UTC, merged