HW07 is completed
yakuninmax/otus_go pull request #8
Opened 2024-06-06 19:25 UTC by yakuninmax

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-06-07 00:13 UTC, dshemin requested changes

2024-06-07 00:13 UTC, dshemin commented on hw07_file_copying/go.mod
>  module github.com/fixme_my_friend/hw07_file_copying
Критично:

Не исправлено название модуля.

2024-06-07 00:13 UTC, dshemin commented on hw07_file_copying/copy.go
>  func Copy(fromPath, toPath string, offset, limit int64) error {
Важно:

Что будет если передать offset < 0? Или limit < 0? Надо обработать и написать тесты.

Так же, перед тем как копировать, надо убедится что fromPath и toPath не указывают на один и тот же файл. Сразу подскажу что сравнение строк - не верное решени.

2024-06-07 00:13 UTC, dshemin commented on hw07_file_copying/copy.go
> +	_, err = sourceFile.Seek(offset, 0)
Важно:

Вместо 0 можно использовать именованную константу https://pkg.go.dev/io#pkg-constants

2024-06-07 00:13 UTC, dshemin commented on hw07_file_copying/copy_test.go
> +				assert.Equal(t, md5checksum(t, test.referenceFile), md5checksum(t, tempFile.Name()))
Важно:

Зачем нам тут считать хеш файла, можно просто сравнить содержимое напрямую.

2024-06-07 12:16 UTC, yakuninmax commented
Устранил замечания.

2024-06-08 02:47 UTC, dshemin approved these changes

2024-06-17 17:41 UTC, merged